<a href="https://colab.research.google.com/github/korjjs/Python-Pandas/blob/master/random%20%EB%AA%A8%EB%93%88%20%EC%A0%95%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#numpy 의 np.random. randint vs rand/randn

##np.random.seed seed를 통한 난수 생성

---
np.random.randint 균일 분포의 정수 난수 1개 생성

np.random.rand 0부터 1사이의 균일 분포에서 난수 matrix array생성

np.random.randn 가우시안 표준 정규 분포에서 난수 matrix array생성

---

np.random.shuffle 기존의 데이터의 순서 바꾸기

np.random.choice 기존의 데이터에서 sampling

np.unique 데이터에서 중복된 값을 제거하고 중복되지 않는 값의 리스트를 출력

np.bincount 발생하지 않은 사건에 대해서도 카운트를 해준다.


In [0]:
import numpy as np

## random.randint 와 np.random.randint 
### : 모두 (시작, n-1) 사이의 랜덤숫자 1개 뽑아내기

In [2]:
np.random.randint(6) # 0 or 1 or ~ or 5      0부터 5까지 랜덤한 숫자 1개

5

In [3]:
np.random.randint(1, 20) # 1부터 19까지 랜덤숫자 1개

8

## np.random.rand(m,n) 
###: 0 ~ 1의 균일분포 표준정규분포 난수를 matrix array(m,n) 생성

In [4]:
np.random.rand(6)  

array([0.06762508, 0.51578957, 0.55626709, 0.17185406, 0.3935646 ,
       0.10256136])

In [5]:
np.random.rand(3,2)

array([[0.02580374, 0.34257134],
       [0.71942744, 0.78492265],
       [0.0311088 , 0.06141104]])

## np.random.randn(m,n) 
### : 평균0, 표준편차1의 가우시안 표준정규분포 난수를 matrix array(m,n) 생성

In [6]:
np.random.randn(6)

array([-1.14244088, -1.13458799, -0.34788101,  0.42586245, -1.10542334,
        1.47779753])

In [7]:
np.random.randn(3, 2)

array([[ 0.52231252,  0.04329461],
       [ 0.77415906, -0.0631387 ],
       [ 0.88495981,  0.76615918]])